# Site
repository: sproogen/resume-theme
favicon: images/peng.ico

# Content configuration version
version: 2

# Personal info
name: 박지현
title: DevOps 엔지니어
email: hyoni0712@gmail.com
# website: https://github.com/hyoniiii

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  hyoniiii
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: 
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  ## <b>Introduction</b>
  끊임없이 고민하는 DevOps 엔지니어 박지현 입니다.
  - 내용
  
  ---

  ## <b>This is me</b>
  - [활발한 의사소통으로](https://aerial-bamboo-7ba.notion.site/This-is-ME-e05f0aa698284d8b8d25e6e566d0a501) 팀 분위기를 이끌어 갑니다.
  - 현재에 안주하지 않고 끊임없이 발전합니다.
  - 모르는 내용은 끝까지 이해하고 넘어갑니다.

  ---

  ## <b>My Vision</b>
  - 내용

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 클라우드 마이그레이션
        link: github.com/sproogen
        # link_text: Project Website
        sub_title: Migration from On-premise to AWS
        caption: 2022.07.25 ~ 2022.08.04
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          클라이언트 요구사항에 따라 온프레미스 환경에서 설치 및 운영되고 있는 사내 정보 시스템을 클라우드로 이관
        description: | # this will include new lines to allow paragraphs
          - JWT를 이용한 통합 인증 제공(Authorizer Lambda)
          - HTTP 요청에 대한 응답 데이터를 Private Subnet에 구축하여 보안성 강화
          - Application Load Balancer를 사용하여 <mark>트래픽 초과 대응</mark>
          - <mark>FinOps의 관점으로 아키텍쳐 분석</mark> 후 [CloudMap](https://aerial-bamboo-7ba.notion.site/HTTP-Private-Subnet-a0a08b67b6744e3591af2b0824c38bc0), VPC endpoint를 이용하여 예산 절감
          - Code Deploy, Github Action을 사용하여 개발자를 위한 코드 배포 자동화 구현
          - Stack : API Gateway, Lambda, EC2, ECS, ECR, DynamoDB, RDS, CloudMap, VPC endpoint, SSM, ALB
      - layout: left
        title: MSA CI/CD 파이프라인 구축
        link: aaa
        sub_title: 
        caption: 2022.07.07 ~ 2022.07.12
        quote: >
          자동 재고 확보 시스템을 MSA로 구축
        description: |
           - Serverless를 이용하여 메세지 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 코드스테이츠
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: DevOps 부트캠프 2기
        caption: 2022.04 ~ 2022.08
        # quote: >
        #   DevOps 엔지니어에게 필요한 기본 개념 및 배포 환경 구성 교육
        description: | # this will include new lines to allow paragraphs
            - 애플리케이션 컨테이너화
            - 컨테이너 오케스트레이션
            - AWS 서비스를 이용하여 애플리케이션 작동을 위한 인프라 구성
            - CI/CD 툴을 통한 배포 자동화
            - IaC를 이용해 인프라를 코드로 구성
            - HTTP를 이해하고, REST API 작성
            - 애플리케이션 간 느슨한 결합 설계
            - 코드 버전 관리
            - 서비스와 관련된 지표 모니터링
            - 모니터링 구축
            - 마이크로서비스 아키텍쳐에 대한 이해
            - Public/Private 클라우드 네트워크 구성에 대한 이해

  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
        quote: >
          현재 사용 가능한 기술들 입니다.
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - Docker
          - Kubernetes
          - Terraform
          - Prometheus, Grafana
          - k6
          - Nginx, Apache
        #
      - layout: left
        title: AWS
        description: |
          - EC2
          - Lambda
          - ECS
          - ECR
          - Cloudformation
          - S3
          - SNS, SQS
          - VPC, Route53, Cloudfront, API_Gateway
          - CodeCommit, CodeBuild, CodeDeploy, CodePipeline
      - layout: left
        title: Backend
        description: |
          - Node.js, express, fastify
      - layout: left
        title: Frontend
        description: |
          - html
          - css
          - javascript, jquery


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      개발 이외에도 손으로 만드는 건 다 좋아합니다!
      - 그림
      - 뜨개질
      - 독서
      - 수영
      - 헬스

      Look at this cool image  
    
    # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
