# Site
repository: sproogen/resume-theme
favicon: images/peng.ico

# Content configuration version
version: 2

# Personal info
name: 박지현
title: Frontend Developer
email: hyoni0712@gmail.com
# website: https://github.com/hyoniiii

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  hyoniiii
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: 
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# 내가 파견 나가서 어떤 프로젝트를 진행했을 때,(비교군 : 잘한거, 문제해결한거, 업무를 많이 한거)
# 100프로만 하면 되는데 120프로까지 해서 인정받았다.(중복된 내용이 첨부되지 않게 조심!)
# ~ 할 때도 제안을 받은 적이 있다.
# 비중을 어디에 둘건지 생각하기! 하나는 짧게
# 그거 인정 받아서 프론트로 담당했다.
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  ## <b>Introduction</b>
  - 결과를 눈으로 확인하며 개발하는 것이 프론트의 가장 큰 매력이라고 생각합니다.
  다양한 사용자들의 피드백을 받으며 생각과 시야가 넓어지는 것을 좋아합니다.
  - SI 업체에서 3년 동안 근무한 경험이 있습니다. 
  처음에는 퍼블리셔로 시작했지만, 회사의 제안을 받아 프론트 쪽 까지 담당하였습니다.
  또한 1년차 때 3년차의 업무를 소화해내며 협력 업체에서 스카웃을 받은 적도 있습니다.
  - 프론트 개발자로 직무 전환을 하며 협업을 하던 중 서버나 DB에 대한 보다 깊이 있는 이해도가 필요하다고 판단해
  DevOps 과정을 수료하였습니다.

  ---

  ## <b>This is me</b>
  - 반응형 및 적응형 웹에 대한 경험과 이해가 있습니다.
  - 사용자의 관점에서 UI와 UX를 고민하고 개발할 수 있습니다.
  - Restful API에 대한 이해와 개발 경험이 있습니다.
  - HTML5, CSS등의 W3C 웹표준/웹접근성 이해도가 있습니다.
  - React, Vue.js 등 을 이용한 SPA / CSR Front-End 개발 역량이 있습니다.
  - WAS(Web Application Server)를 통해 사용자의 요청에 맞게 정적 컨텐츠와 동적 컨텐츠를 제공할 수 있습니다.
  - 인프라, MSA에 대한 기본적인 지식을 갖추고 있습니다.
  - CI/CD 파이프 라인을 통한 자동화와 테스트 환경 자동화 구축이 가능합니다.
  - [리더와 서폿 모든 포지션이 가능한](https://aerial-bamboo-7ba.notion.site/This-is-ME-e05f0aa698284d8b8d25e6e566d0a501) 올라운더입니다.
  - 적극적인 의견 제시와 활발한 회의 문화를 만들어 나가는 것을 좋아합니다. (자사 홈페이지 개편 ppt 첨부)

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: 렉터슨
        sub_title: 웹서비스 화면 구축 및 UI/UX 디자인
        caption: 2019.08 ~ 2022.03
        quote: >
          에너지 회사
        description: |
          - 창원 RE100 신재생 에너지
            - SK C&C가 주관하는 300억 규모의 RE100 사업
            - 창원 산단 내의 n개의 공장을 대상으로 B2B 모니터링 웹 플랫폼 구축
            - Stack : HTML,CSS,Javascript,Jquery,Chart.js
          - 도로 비탈면 상시계측 시스템
            - HTML,CSS,Javascript,Jquery,Chart.js를 사용하여 
          - 압력 용기
            - HTML
          - 자사 홈페이지 개편
            - 기획, 디자인 및 구현
      - layout: left
        title: 에이치엘스토리
        sub_title: 웹 퍼블리싱
        caption: 2019.05 ~ 2019.07
        quote: >
          홈페이지 제작 회사
        description: |
          - 기존 홈페이지 템플릿 유지보수 및 퍼블리싱
            - 사이트 몇개
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 클라우드 마이그레이션
        link: github.com/sproogen
        # link_text: Project Website
        sub_title: Migration from On-premise to AWS
        caption: 2022.07.25 ~ 2022.08.04
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          클라이언트 요구사항에 따라 온프레미스 환경에서 설치 및 운영되고 있는 사내 정보 시스템을 클라우드로 이관
        description: | # this will include new lines to allow paragraphs
          - JWT를 이용한 통합 인증 제공(Authorizer Lambda)
          - HTTP 요청에 대한 응답 데이터를 Private Subnet에 구축하여 보안성 강화
          - Application Load Balancer를 사용하여 <mark>트래픽 초과 대응</mark>
          - <mark>FinOps의 관점으로 아키텍쳐 분석</mark> 후 [CloudMap](https://aerial-bamboo-7ba.notion.site/HTTP-Private-Subnet-a0a08b67b6744e3591af2b0824c38bc0), VPC endpoint를 이용하여 예산 절감
          - Code Deploy, Github Action을 사용하여 개발자를 위한 코드 배포 자동화 구현
          - Stack : API Gateway, Lambda, EC2, ECS, ECR, DynamoDB, RDS, CloudMap, VPC endpoint, SSM, ALB
      
      - layout: left
        title: MSA CI/CD 파이프라인 구축
        link: aaa
        sub_title: 
        caption: 2022.07.07 ~ 2022.07.12
        quote: >
          자동 재고 확보 시스템을 MSA로 구축
        description: |
           - Serverless를 이용하여 메세지 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 코드스테이츠
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: DevOps 부트캠프 2기
        caption: 2022.04 ~ 2022.08
        # quote: >
        #   DevOps 엔지니어에게 필요한 기본 개념 및 배포 환경 구성 교육
        description: | # this will include new lines to allow paragraphs
          - 애플리케이션 컨테이너화
          - 컨테이너 오케스트레이션
          - AWS 서비스를 이용하여 애플리케이션 작동을 위한 인프라 구성
          - CI/CD 툴을 통한 배포 자동화
          - IaC를 이용해 인프라를 코드로 구성
          - HTTP를 이해하고, REST API 작성
          - 애플리케이션 간 느슨한 결합 설계
          - 코드 버전 관리
          - 서비스와 관련된 지표 모니터링
          - 모니터링 구축
          - 마이크로서비스 아키텍쳐에 대한 이해
          - Public/Private 클라우드 네트워크 구성에 대한 이해
      - layout: left
        title: 그린컴퓨터아카데미
        sub_title: 디지털컨버전스(UI/UX엔지니어링)<br>프론트엔드개발자과정
        caption: 2018.10 ~ 2019.03
        description: |
          - 사용자의 이용 행태와 트렌드 및 기술 환경을 분석
          - 새로운 사용자 경험(UX) 모델 제시
          - UI/UX 계획, 실 사용자 리서치, 사용자 인터페이스(UI) 기획 
          - UI 아키텍처 설계, UI 디자인, UI 구현, 프로토타입 검증을 거쳐 가이드 제작

  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
        quote: >
          현재 사용 가능한 기술들 입니다.
      - layout: left
        title: Frontend
        description: |
          - html
          - css
          - javascript, jquery
      - layout: left
        title: Backend
        description: |
          - Node.js, express, fastify
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - Docker
          - Kubernetes
          - Terraform
          - Prometheus, Grafana
          - k6
          - Nginx, Apache
        #
      - layout: left
        title: AWS
        description: |
          - EC2
          - Lambda
          - ECS
          - ECR
          - Cloudformation
          - S3
          - SNS, SQS
          - VPC, Route53, Cloudfront, API_Gateway
          - CodeCommit, CodeBuild, CodeDeploy, CodePipeline


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      개발 이외에도 손으로 만드는 건 다 좋아합니다!
      - 그림
      - 뜨개질
      - 수영
      - 헬스
    # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
